In [11]:
import pandas as pd
import numpy as np
import random

In [12]:
df = pd.read_csv('../data/processed_data/all/resample_to_50_per_act/resample_to_50_with_big_seg.csv')
df.tail()

,x,y,z,label,seg,suspicious
251295,-928.094685,163.788475,337.651526,clean,clean/庆喜/repeat_82-duration_60,False
251296,-946.717057,177.251312,326.688697,clean,clean/庆喜/repeat_82-duration_60,False
251297,-933.746906,167.946609,310.380039,clean,clean/庆喜/repeat_82-duration_60,False
251298,-910.344399,154.584634,309.409075,clean,clean/庆喜/repeat_82-duration_60,False
251299,-896.701663,143.548819,302.866383,clean,clean/庆喜/repeat_82-duration_60,False

In [13]:
segs =df.seg.unique()
segs

array(['walk/863137003295439_walk_L_2017-07-25 17-39-00_2017-07-25 17-49-00',
       'bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-07-20 15-00-00_2017-07-20 15-10-00',
       'clean/铲除小广告/右手蹲着左右铲小广告/863137003295140_2017-07-06 10-37-00_2017-07-06 10-40-00',
       'sweep/小扫帚扫地/小扫帚左手左侧往前扫第一组/男/863137003295439_2017-06-30 16_56_2017-06-30 16_59',
       'bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003291982_2017-06-30 15-05-00_2017-06-30 15-08-20',
       'daily/863137003294663_2017-07-18 15-00-00_2017-07-18 21-00-00',
       'bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003295439_2017-06-30 15-05-00_2017-06-30 15-08-20',
       'sweep/小扫帚扫地/小扫帚左手横着扫第一组/男/863137003295439_2017-06-30 16_53_2017-06-30 16_56',
       'clean/擦垃圾桶/右手擦垃圾桶上下/863137003292337_2017-07-05 19-10-00_2017-07-05 19-13-00',
       'clean/铲除小广告/右手蹲着前后铲小广告/863137003295140_2017-07-06 11-03-00_2017-07-06 11-06-00',
       'bweep/大扫帚扫地/大扫帚扫右手高位第一组/男/863137003294663_2017-06-30 14-49-00_2017-06-30 14-53-00',
       'bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003298748_2017-07-20 16-20-00_2017-07-20 16-55-00',
       'clean/铲除小广告/左右手站立铲小广告/863137003295140_2017-07-06 14-27-00_2017-07-06 14-30-00',
       'walk/863137003294663_walk_R_2017-07-25 17-41-30_2017-07-25 17-44-30',
       'bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003290836_2017-07-20 17-20-00_2017-07-20 17-40-00',
       'bweep/大扫帚推地/大扫帚推右手低位第一组/男/863137003291982_2017-06-30 15-02-30_2017-06-30 15-06-00',
       'bweep/大扫帚扫地/大扫帚扫右手低位第二组/男/863137003291982_2017-06-30 14-28-30_2017-06-30 14-32-30',
       'bweep/大扫帚扫地/大扫帚扫右手低位第二组/男/863137003295439_2017-06-30 14-28-00_2017-06-30 14-32-30',
       'dump/863137003292378_2017-07-17 17-41-30_2017-07-17 17-52-00',
       'bweep/大扫帚扫地/大扫帚扫右手高位第一组/男/863137003291982_2017-06-30 14-49-00_2017-06-30 14-53-00',
       'bweep/大扫帚扫地/大扫帚扫右手高位第二组/男/863137003294663_2017-06-30 14-52-00_2017-06-30 14-56-10',
       'bweep/大扫帚扫地/大扫帚扫左手高位第二组/男/863137003295439_2017-06-30 16_48_2017-06-30 16_51',
       'run/863137003294663_running_R_2017-07-25 17-58-00_2017-07-25 18-03-00',
       'bweep/大扫帚推地/大扫帚推右手低位第一组/男/863137003294663_2017-06-30 15-02-30_2017-06-30 15-06-00',
       'dump/右手抓边，左手托底倒垃圾桶/863137003292378_2017-07-17 17-30-30_2017-07-17 17-47-00',
       'bweep/大扫帚推地/大扫帚推右手高位第二组/男/863137003291982_2017-06-30 15-23-30_2017-06-30 15-26-15',
       'bweep/大扫帚推地/大扫帚推右手高位第一组/女/863137003292949_2017-06-30 15-21-30_2017-06-30 15-24-30',
       'clean/铲除小广告/左手蹲着左右铲小广告/863137003295140_2017-07-06 14-39-00_2017-07-06 14-43-00',
       'bweep/大扫帚扫地/大扫帚扫右手低位第二组/男/863137003294663_2017-06-30 14-28-00_2017-06-30 14-32-30',
       'bweep/大扫帚推地/大扫帚推右手低位第一组/男/863137003295439_2017-06-30 15-02-30_2017-06-30 15-06-00',
       'bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-07-20 15-30-00_2017-07-20 15-40-00',
       'dump/双手扶垃圾桶中间/863137003295140_2017-07-06 13-31-00_2017-07-06 13-34-00',
       "daily/swing/863137003291982_swing one's arms_R_2017-07-25 17-55-00_2017-07-25 17-57-00",
       'dump/双手扶垃圾桶中间/863137003292337_2017-07-06 15-08-00_2017-07-06 15-12-00',
       'clean/刷小广告/左手站立刷左右刷/863137003295140_2017-07-05 18-01-30_2017-07-05 18-05-00',
       'walk/863137003291982_walk_R_2017-07-25 17-41-30_2017-07-25 17-44-30',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第一组/女/863137003292949_2017-06-30 16_09_2017-06-30 16_13',
       'clean/刷小广告/左手站立刷上下刷/863137003295140_2017-07-05 17-52-30_2017-07-05 17-56-00',
       'bweep/大扫帚扫地/大扫帚扫右手低位第一组/女/863137003292949_2017-06-30 14-25-00_2017-06-30 14-28-30',
       'bweep/大扫帚扫地/大扫帚扫右手高位第一组/女/863137003292949_2017-06-30 14-49-00_2017-06-30 14-53-00',
       'bweep/大扫帚扫地/大扫帚扫右手低位第一组/男/863137003294663_2017-06-30 14-25-00_2017-06-30 14-28-30',
       'bweep/大扫帚扫地/大扫帚扫右手高位第二组/男/863137003291982_2017-06-30 14-52-00_2017-06-30 14-56-10',
       'clean/铲除小广告/左右手站立铲小广告/863137003295140_2017-07-06 11-18-00_2017-07-06 11-21-00',
       'sweep/小扫帚扫地/小扫帚右手横着扫第二组/女/863137003292949_2017-06-30 16_02_2017-06-30 16_06',
       'bweep/大扫帚扫地/大扫帚扫右手高位第一组/男/863137003295439_2017-06-30 14-49-00_2017-06-30 14-53-00',
       'clean/刷小广告/右手蹲着刷左右刷/863137003292337_2017-07-05 18-29-00_2017-07-05 18-32-00',
       'bweep/大扫帚推地/大扫帚推右手高位第一组/男/863137003291982_2017-06-30 15-21-00_2017-06-30 15-24-00',
       'bweep/大扫帚推地/大扫帚推右手高位第一组/男/863137003294663_2017-06-30 15-21-20_2017-06-30 15-24-00',
       'bweep/大扫帚扫地/大扫帚扫右手低位第一组/男/863137003295439_2017-06-30 14-25-00_2017-06-30 14-28-30',
       'sweep/小扫帚扫地/小扫帚右手横着扫第一组/女/863137003292949_2017-06-30 15_51_2017-06-30 15_56',
       'dump/863137003291982_2017-07-17 17-50-00_2017-07-17 18-00-00',
       'bweep/大扫帚推地/大扫帚推右手低位第二组/女/863137003292949_2017-06-30 15-05-00_2017-06-30 15-08-20',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第二组/男/863137003291982_2017-06-30 16_17_2017-06-30 16_21',
       'clean/擦垃圾桶/右手擦垃圾桶画圆/863137003295140_2017-07-05 18-55-30_2017-07-05 18-59-00',
       'clean/擦垃圾桶/右手擦垃圾桶画圆/863137003292337_2017-07-05 19-16-00_2017-07-05 19-19-00',
       'sweep/小扫帚扫地/小扫帚右手横着扫第一组/男/863137003295439_2017-06-30 15_51_2017-06-30 15_56',
       'bweep/大扫帚扫地/大扫帚扫右手低位第二组/女/863137003292949_2017-06-30 14-28-00_2017-06-30 14-32-30',
       'dump/右手抓边，左手托底倒垃圾桶/863137003291982_2017-07-17 17-29-00_2017-07-17 17-39-00',
       'clean/刷小广告/左手蹲着刷左右刷/863137003295140_2017-07-05 18-39-00_2017-07-05 18-42-00',
       "daily/swing/863137003294663_swing one's arms_R_2017-07-25 17-55-00_2017-07-25 17-57-00",
       'bweep/大扫帚扫地/大扫帚扫左手低位第二组/男/863137003295439_2017-06-30 16_35_2017-06-30 16_38',
       'sweep/小扫帚扫地/小扫帚右手横着扫第二组/男/863137003294663_2017-06-30 16_02_2017-06-30 16_06',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第一组/男/863137003295439_2017-06-30 16_09_2017-06-30 16_13',
       'dump/右手抓边，左手托底倒垃圾桶/863137003295140_2017-07-06 13-19-00_2017-07-06 13-23-00',
       'clean/铲除小广告/左手蹲着前后铲小广告/863137003295140_2017-07-06 14-33-00_2017-07-06 14-36-00',
       'bweep/大扫帚扫地/大扫帚扫右手高位第二组/男/863137003295439_2017-06-30 14-52-00_2017-06-30 14-56-10',
       'bweep/大扫帚推地/大扫帚推右手低位第一组/女/863137003292949_2017-06-30 15-04-00_2017-06-30 15-06-30',
       'bweep/大扫帚推地/大扫帚推右手（现场部署）/863137003290778_2017-07-21 09-20-00_2017-07-21 09-30-00',
       'bweep/大扫帚扫地/大扫帚扫右手高位第二组/女/863137003292949_2017-06-30 14-52-00_2017-06-30 14-56-10',
       'bweep/大扫帚扫地/大扫帚扫右手低位第一组/男/863137003291982_2017-06-30 14-25-00_2017-06-30 14-28-30',
       'clean/刷小广告/右手站立刷左右刷/863137003295140_2017-07-05 17-46-00_2017-07-05 17-49-00',
       'bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003291263_2017-07-21 10-08-00_2017-07-21 10-30-00',
       'run/863137003291982_running_R_2017-07-25 17-58-00_2017-07-25 18-03-00',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第二组/女/863137003292949_2017-06-30 16_17_2017-06-30 16_21',
       'bweep/大扫帚推地/大扫帚推右手高位第一组/男/863137003295439_2017-06-30 15-21-20_2017-06-30 15-24-00',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第二组/男/863137003294663_2017-06-30 16_17_2017-06-30 16_21',
       'clean/铲除小广告/右手蹲着前后铲小广告/863137003295140_2017-07-06 14-19-00_2017-07-06 14-22-00',
       'clean/铲除小广告/左手蹲着前后铲小广告/863137003295140_2017-07-06 11-52-00_2017-07-06 11-55-00',
       'bweep/大扫帚扫地/大扫帚扫左手低位第一组/男/863137003295439_2017-06-30 16_24_2017-06-30 16_31',
       'daily/863137003292337_2017-07-18 15-00-00_2017-07-18 21-00-00',
       'clean/擦垃圾桶/右手擦垃圾桶上下/863137003295140_2017-07-05 18-53-00_2017-07-05 18-56-00',
       'clean/刷小广告/左手蹲着刷上下刷/863137003295140_2017-07-05 18-34-00_2017-07-05 18-37-00',
       'clean/刷小广告/右手站立刷上下刷/863137003295140_2017-07-05 17-42-00_2017-07-05 17-45-00',
       'sweep/小扫帚扫地/小扫帚右手横着扫第一组/男/863137003291982_2017-06-30 15_51_2017-06-30 15_56',
       'sweep/小扫帚扫地/小扫帚右手横着扫第一组/男/863137003294663_2017-06-30 15_51_2017-06-30 15_56',
       'bweep/大扫帚推地/大扫帚推右手高位第二组/男/863137003292949_2017-06-30 15-23-30_2017-06-30 15-26-40',
       'bweep/大扫帚扫地/大扫帚扫左手高位第一组/男/863137003295439_2017-06-30 16_43_2017-06-30 16_47',
       'sweep/小扫帚扫地/小扫帚扫右手（现场部署）/863137003290778_2017-07-20 15-54-00_2017-07-20 16-04-00',
       'sweep/小扫帚扫地/小扫帚扫右手（现场部署）/863137003290638_2017-07-20 17-05-00_2017-07-20 17-15-00',
       'clean/擦垃圾桶/右手擦垃圾桶左右/863137003295140_2017-07-05 18-50-00_2017-07-05 18-53-00',
       'clean/刷小广告/右手站立刷左右刷/863137003292337_2017-07-05 17-37-00_2017-07-05 17-40-00',
       'sweep/小扫帚扫地/小扫帚扫右手（现场部署）/863137003293509_2017-07-20 16-09-00_2017-07-20 16-19-00',
       'clean/擦垃圾桶/右手擦垃圾桶左右/863137003292337_2017-07-05 19-00-00_2017-07-05 19-03-00',
       'clean/铲除小广告/左手蹲着左右铲小广告/863137003295140_2017-07-06 11-58-00_2017-07-06 12-01-00',
       'sweep/小扫帚扫地/小扫帚扫右手（现场部署）/863137003297617_2017-07-21 09-39-00_2017-07-21 09-49-00',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第二组/男/863137003295439_2017-06-30 16_17_2017-06-30 16_21',
       'sweep/小扫帚扫地/小扫帚右手横着扫第二组/男/863137003291982_2017-06-30 16_02_2017-06-30 16_06',
       'bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003294663_2017-06-30 15-05-00_2017-06-30 15-08-20',
       'clean/刷小广告/右手站立刷上下刷/863137003292337_2017-07-05 17-24-00_2017-07-05 17-28-00',
       'clean/铲除小广告/右手蹲着左右铲小广告/863137003295140_2017-07-06 14-11-00_2017-07-06 14-14-00',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第一组/男/863137003294663_2017-06-30 16_09_2017-06-30 16_13',
       'dump/右手抓边，左手托底倒垃圾桶/863137003292337_2017-07-06 15-02-00_2017-07-06 15-05-00',
       'sweep/小扫帚扫地/小扫帚右手右侧往前扫第一组/男/863137003291982_2017-06-30 16_09_2017-06-30 16_13',
       'sweep/小扫帚扫地/小扫帚右手横着扫第二组/男/863137003295439_2017-06-30 16_02_2017-06-30 16_06',
       'bweep/右手高位大扫帚扫/repeat_77-duration_120',
       'bweep/右手低位大扫帚扫/repeat_70-duration_120',
       'sweep/右手小扫帚扫/repeat_124-duration_120',
       'bweep/右手高位大扫帚扫/repeat_96-duration_120',
       'clean/右手擦垃圾桶/repeat_60-duration_60',
       'sweep/右手小扫帚扫/repeat_144-duration_120',
       'clean/右手擦垃圾桶/repeat_50-duration_60',
       'sweep/右手小扫帚扫/repeat_140-duration_120',
       'dump/右手托底倒垃圾桶/repeat_60-duration_60',
       'bweep/右手高位大扫帚扫/repeat_95-duration_120',
       'dump/右手抓垃圾桶边缘倒/repeat_22-duration_60',
       'dump/右手抓垃圾桶边缘倒/repeat_19-duration_60',
       'clean/右手擦垃圾桶/repeat_80-duration_60',
       'sweep/右手小扫帚扫/repeat_125-duration_120',
       'dump/双手抱垃圾桶/repeat_17-duration_60',
       'sweep/右手小扫帚扫/repeat_150-duration_120',
       'sweep/右手小扫帚扫/repeat_85-duration_120',
       'bweep/右手高位大扫帚扫/repeat_51-duration_120',
       'bweep/右手高位大扫帚扫/repeat_80-duration_120',
       'dump/右手托底倒垃圾桶/repeat_15-duration_60',
       'clean/右手擦垃圾桶/repeat_120-duration_120',
       'sweep/右手小扫帚扫/repeat_105-duration_120',
       'bweep/右手低位大扫帚扫/repeat_75-duration_120',
       'clean/庆喜/repeat_61-duration_60', 'dump/倒垃圾/repeat_16-duration_60',
       'bweep/大扫帚右手高位/repeat_25-duration_60',
       'daily/放在口袋走/repeat_00-duration_301',
       'bweep/大扫帚右手高位/高志勇/repeat_86-duration_60',
       'sweep/右手小扫帚/庆喜/repeat_56-duration_60',
       'dump/倒垃圾/repeat_19-duration_60', 'clean/海新/repeat_70-duration_60',
       'sweep/右手小扫帚/庆喜/repeat_55-duration_60',
       'dump/倒垃圾/repeat_23-duration_60', 'dump/倒垃圾/repeat_21-duration_60',
       'clean/海新/repeat_69-duration_60',
       'bweep/大扫帚右手高位/repeat_27-duration_60',
       'sweep/右手小扫帚/海新/repeat_65-duration_74',
       'dump/倒垃圾/repeat_22-duration_60',
       'sweep/右手小扫帚/海新/repeat_60-duration_60',
       'clean/海新/repeat_71-duration_60',
       'daily/放在口袋走/repeat_00-duration_300',
       'clean/庆喜/repeat_82-duration_60'], dtype=object)

In [14]:
seg0 = segs[0]
seg_df0 = df[df['seg']==seg0][['x', 'y', 'z', 'label', 'seg']]
seg_df0.shape
seg_df0.tail()

(4300, 5)

,x,y,z,label,seg
4295,-107.982576,412.219888,904.629416,walk,walk/863137003295439_walk_L_2017-07-25 17-39-0...
4296,-95.036085,386.317495,912.904104,walk,walk/863137003295439_walk_L_2017-07-25 17-39-0...
4297,-106.666899,415.517984,904.564437,walk,walk/863137003295439_walk_L_2017-07-25 17-39-0...
4298,-112.742574,420.520652,901.965533,walk,walk/863137003295439_walk_L_2017-07-25 17-39-0...
4299,-110.271773,411.792062,900.121959,walk,walk/863137003295439_walk_L_2017-07-25 17-39-0...

In [15]:
seg1 = segs[1]
seg_df1 = df[df['seg']==seg1][['x', 'y', 'z', 'label', 'seg']]
seg_df1.shape
seg_df1.head()

(3250, 5)

,x,y,z,label,seg
4300,19.000000,225.000000,804.000000,bweep,bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-...
4301,27.062843,246.856767,740.492202,bweep,bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-...
4302,12.409253,438.759436,808.643267,bweep,bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-...
4303,47.775776,821.475801,900.977725,bweep,bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-...
4304,-12.654518,727.270889,636.311594,bweep,bweep/大扫帚扫地/大扫帚扫右手（现场部署）/863137003297617_2017-...

In [16]:
new_df = pd.concat([seg_df0, seg_df1], axis=0)
new_df.shape
new_df[9424:9428]

(7550, 5)

Empty DataFrame
Columns: [x, y, z, label, seg]
Index: []

In [17]:
cols = df.columns.values[:5]
all_df = pd.DataFrame(columns=cols)
train_df = pd.DataFrame(columns=cols)
test_df = pd.DataFrame(columns=cols)
all_df

Empty DataFrame
Columns: [x, y, z, label, seg]
Index: []

In [18]:
%%time
seg_len = 50
for seg in segs:
    seg_df = df[df['seg']==seg][['x', 'y', 'z', 'label', 'seg']]
    
    train_num = round(len(seg_df)/seg_len*9/10)  
    train_len = train_num * seg_len
    
    tmp_train_df = seg_df.iloc[:train_len]
    tmp_test_df = seg_df.iloc[train_len:]
    
    all_df = pd.concat([all_df, seg_df], axis=0)
    train_df = pd.concat([train_df, tmp_train_df], axis=0)
    test_df = pd.concat([test_df, tmp_test_df], axis=0)

Wall time: 8.17 s

In [19]:
all_df.shape
train_df.shape
test_df.shape
all_df.tail()

(251300, 5)

(226150, 5)

(25150, 5)

,x,y,z,label,seg
251295,-928.094685,163.788475,337.651526,clean,clean/庆喜/repeat_82-duration_60
251296,-946.717057,177.251312,326.688697,clean,clean/庆喜/repeat_82-duration_60
251297,-933.746906,167.946609,310.380039,clean,clean/庆喜/repeat_82-duration_60
251298,-910.344399,154.584634,309.409075,clean,clean/庆喜/repeat_82-duration_60
251299,-896.701663,143.548819,302.866383,clean,clean/庆喜/repeat_82-duration_60

In [20]:
all_df.to_csv('../data/processed_data/all/resample_to_50_per_act/file_split/all.csv', index=False)
train_df.to_csv('../data/processed_data/all/resample_to_50_per_act/file_split/train.csv', index=False)
test_df.to_csv('../data/processed_data/all/resample_to_50_per_act/file_split/test.csv', index=False)

In [21]:
new_df1 = pd.read_csv('../data/processed_data/all/resample_to_50_per_act/file_split/all.csv')
new_df1[9424:9428]

,x,y,z,label,seg
9424,-513.850705,299.675891,-799.230244,bweep,bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003291982_2017...
9425,-540.210091,285.834846,-710.376597,bweep,bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003291982_2017...
9426,-553.981871,324.149719,-629.723011,bweep,bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003291982_2017...
9427,-540.030550,326.304270,-627.197926,bweep,bweep/大扫帚推地/大扫帚推右手低位第二组/男/863137003291982_2017...