In [1]:
import pandas as pd
import numpy as np
import math

from feature import feature_extraction
from feature import feature_normalization

In [2]:
tmp_df = pd.read_csv('../data/processed_data/all/resample_to_50_per_act/file_split/train.csv')
tmp_df_len = len(tmp_df)
tmp_df_len

226150

In [3]:
subw_size = 50
subw_step = 50
subw_num = math.floor(tmp_df_len/subw_step)-1
subw_num
df_len = subw_step*(subw_num+1)
df_len
df = tmp_df.iloc[:df_len]
df.tail()

4522

226150

,x,y,z,label,seg
226145,-693.625119,-107.375606,881.284901,clean,clean/庆喜/repeat_82-duration_60
226146,-735.426617,-46.907018,588.535043,clean,clean/庆喜/repeat_82-duration_60
226147,-696.228786,9.813581,678.342501,clean,clean/庆喜/repeat_82-duration_60
226148,-543.576762,62.398923,1120.661357,clean,clean/庆喜/repeat_82-duration_60
226149,-522.924555,115.675546,1098.997249,clean,clean/庆喜/repeat_82-duration_60

In [4]:
cols = ['label', 
        'sum_x', 'sum_y', 'sum_z', \
        'mean_x', 'mean_y', 'mean_z', \
        'std_x', 'std_y', 'std_z', \
        'cv_x', 'cv_y', 'cv_z', \
        'ptp_x', 'ptp_y', 'ptp_z', \
        'p10_x', 'p10_y', 'p10_z', \
        'p25_x', 'p25_y', 'p25_z', \
        'p50_x', 'p50_y', 'p50_z', \
        'p75_x', 'p75_y', 'p75_z', \
        'p90_x',' p90_y', 'p90_z', \
        'iq_x', 'iq_y', 'iq_z', \
        'lagone_autocor_x', 'lagone_autocor_y', 'lagone_autocor_z', \
        'sk_x', 'sk_y', 'sk_z', \
        'kurt_x', 'kurt_y', 'kurt_z', \
        'power_x', 'power_y', 'power_z', \
        'logpower_x', 'logpower_y', 'logpower_z', \
        'peak_x', 'peak_y', 'peak_z', \
        'cross0_x', 'cross0_y', 'cross0_z', \
        'cor_xy', 'cor_yz', 'cor_zx']

In [5]:
%%time
training_data = pd.DataFrame(columns=cols)
start = 0
# end_index = df_len - subw_size + 1
end_index = 5000 + 1
while start < end_index:
    end = start + subw_size
    seg_df = df.iloc[start : end]
    label = seg_df.label.unique()[0] if len(seg_df.label.unique())==1 else 'other'
    x = seg_df['x'].values
    y = seg_df['y'].values
    z = seg_df['z'].values
    features = feature_extraction(x,y,z)
    len_training_data = len(training_data)
    training_data.loc[len_training_data, 'label'] = label
    training_data.loc[len_training_data, 1:] = features

    start += subw_step

Wall time: 636 ms

In [6]:
training_data.tail()

,label,sum_x,sum_y,sum_z,mean_x,mean_y,mean_z,std_x,std_y,std_z,...,logpower_z,peak_x,peak_y,peak_z,cross0_x,cross0_y,cross0_z,cor_xy,cor_yz,cor_zx
96,bweep,16915.9,-496.496,47229.9,338.319,-9.92991,944.599,257.41,92.2876,169.397,...,683.537,4,5,7,6,8,10,0.445007,0.227944,-0.173921
97,bweep,3464.4,-3161.41,46928,69.288,-63.2282,938.56,487.661,197.904,330.373,...,672.256,6,6,6,2,3,7,0.26284,-0.429395,-0.540434
98,bweep,4424.31,-5982.74,49367.8,88.4863,-119.655,987.356,222.842,211.578,189.987,...,687.544,3,4,5,5,4,6,0.764605,-0.161849,0.02571
99,bweep,2808.69,3172.3,49791.9,56.1739,63.4459,995.838,151.571,68.5254,185.257,...,688.644,4,6,4,6,7,6,0.381713,0.121227,-0.129229
100,bweep,6871.13,2076.94,49816.3,137.423,41.5388,996.327,209.649,104.337,189.264,...,688.418,3,6,6,7,10,8,0.695942,-0.345605,-0.213645